version: '2'
services:
  comment_engine-app:
    image: comment_engine
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://comment_engine-postgresql:5432/comment_engine
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  comment_engine-postgresql:
    extends:
      file: postgresql.yml
      service: comment_engine-postgresql
