version: '2'
services:
  comment_engine-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/comment_engine/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=comment_engine
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
